IvyExplicit:
  DataClassFunctions:
    active: true
  DataClassDefaultValues:
    active: true
  DataClassTypedIDs:
    active: true
  NoImplicitFunctionReturnType:
    active: true
  UnnecessaryPassThroughClass:
    active: true
